[profile.default]
optimizer_runs = 1000000
remappings = [
  "@manifoldxyz/=lib/",
  "manifoldxyz/=lib/royalty-registry-solidity/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "create3-factory/=lib/create3-factory/src/",
  "solmate/=lib/solmate/src/",
  "@prb/math/=lib/prb-math/src/",
  "clones-with-immutable-args/=lib/clones-with-immutable-args/src/",
  "ds-test/=lib/clones-with-immutable-args/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "foundry-huff/=lib/foundry-huff/src",
]
verbosity = 1
auto_detect_remappings = false

ffi = true
solc_version = '0.8.20'
evm_version = 'shanghai'

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4
ffi = true
solc_version = '0.8.20'
evm_version = 'shanghai'